/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_orfjackal_thematrixtime_SystemClock */

#ifndef _Included_net_orfjackal_thematrixtime_SystemClock
#define _Included_net_orfjackal_thematrixtime_SystemClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_orfjackal_thematrixtime_SystemClock
 * Method:    getTimeOfDay
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_net_orfjackal_thematrixtime_SystemClock_getTimeOfDay
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     net_orfjackal_thematrixtime_SystemClock
 * Method:    setTimeOfDay
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_net_orfjackal_thematrixtime_SystemClock_setTimeOfDay
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
